[package]
name = "ve"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.97", features = ["backtrace"] }
crossterm = "0.28.1"
loe = "0.3.0"
lsp-client = "0.1.0"
lsp-types = "0.97.0"
lua = "0.0.10"
serde = "1.0.217"
tokio = { version = "1.44.0", features = ["full"] }
